version: "3"

services:
  postgres:
    container_name: "where-did-my-money-go-postgres"
    restart: unless-stopped
    image: "postgres:13"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "pgData:/var/lib/postgresql/data/"

volumes:
  pgData: {}
